Dont_Panic-MVC-API/Dont_Panic-MVC-API/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using Dont_Panic_MVC_API.Models;
using System.Net.Http.Headers;
using Dont_Panic_MVC_API.Models.API_Models;
using Newtonsoft.Json;
using Dont_Panic_MVC_API.Controllers.API_Controllers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.StorageClient;

using System.Configuration;
using System.IO;
using Dont_Panic_MVC_API.API_Models;
using System.Web.Security;

using System.Net.Mail;
using SendGridMail;

namespace Dont_Panic_MVC_API.Controllers


{
   
    public class JobController : Controller
    {

        private JobAPI jobAPI = new JobAPI();

        public ActionResult Browse()
        {
            return View(jobAPI.GetAllJobs().ToList());
        }

        [Authorize]
        public ActionResult Previous()
        {
            return View(jobAPI.GetExpiredUserJobs(User.Identity.GetUserId()).ToList());
        }

        // GET: /Job/
        [Authorize]
        public ActionResult Index()
        {
            IdentityManager im = new IdentityManager();

            if (im.UserContainsRole(User.Identity.GetUserId(),"Provider"))
            {
                JobServiceAPI api = new JobServiceAPI();
                IQueryable<JobService> jobServices = api.getProvidersJobs(User.Identity.GetUserId());
                    
                List<Job> jobs = new List<Job>();
                APIContext context = new APIContext();
                foreach(var jobService in jobServices){
                    jobs.Add(context.Jobs.First(i => i.jobid == jobService.jobid));
                }
                return View(jobs);            
            }
            return View(jobAPI.GetCurrentUserJobs(User.Identity.GetUserId()).ToList());
        }

        // POST: /Job/RepostJob
        [HttpPost]
        public ActionResult RepostJob(int jobid)
        {
            JobAPI api = new JobAPI();
            
            Job job = api.GetJob(jobid);
            if (job != null)
            {
                job.expireDate = DateTime.Now.AddDays(2);
                api.PutJob(jobid, job);
            }
            return RedirectToAction("/");
        }

        // GET: /Job/InterestedPros
        [HttpGet]
        [Authorize]
        public ActionResult InterestedPros(int jobid)
        {

            JobServiceAPI api = new JobServiceAPI();
            IQueryable<JobService> jobproviders = api.getJobsProviders(jobid);

            ServiceAPI sapi = new ServiceAPI();
            APIContext context = new APIContext();

            List<UsersProviderDetails> providers = new List<UsersProviderDetails>();
            foreach (JobService js in jobproviders)
            {
                ServiceProviderDetails detail = context.ServiceProvidersDetails.First(s => s.userId == js.serviceProviderId);
                UsersProviderDetails udetail = new UsersProviderDetails();
                udetail.about = detail.about;
                udetail.address = detail.address;
                udetail.areas_serviced = detail.areas_serviced;
                udetail.availability = detail.availability;
                udetail.business_name = detail.business_name;
                udetail.contact_name = detail.contact_name;
                udetail.contact_number_1 = detail.contact_number_1;
                udetail.contact_number_2 = detail.contact_number_2;
                udetail.description = detail.description;
                udetail.userId = detail.userId;
                udetail.website_address = detail.website_address;
                udetail.username = detail.userName;
                udetail.email = detail.email;
                providers.Add(udetail);
            }
            return View(providers);
        }

        // GET: /Job/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = jobAPI.GetJob(id);

            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: /Job/AcquireLead
        public ActionResult AcquireLead(int jobid)
        {
            APIContext db = new APIContext(); 
            IQueryable<JobService> jobServices = db.jobService.Where(a => a.jobid == jobid);
            
            // If at least one lead has been acquired
            if (jobServices != null) { 
                // Searching if leads have been acquired by this service provider.
                foreach (JobService jobService in jobServices)
                {   // If the service provider already owns a lead for this job then redirect away.
                    if (jobService.serviceProviderId == User.Identity.GetUserId())
                    {
                        return RedirectToAction("/");
                    }
                }
            }

            Job job = jobAPI.GetJob(jobid);
            if (job.leadsAccquired < 3)
            {

                ServiceAPI sapi = new ServiceAPI();
                sapi.removeTokens(1, User.Identity.GetUserId());


                job.leadsAccquired = job.leadsAccquired + 1;
                jobAPI.PutJob(jobid, job);

                JobService servicejob = new JobService();
                servicejob.jobid = jobid;
               
                servicejob.serviceProviderId = User.Identity.GetUserId();
                db.jobService.Add(servicejob);
                db.SaveChanges();
            }
            
            return RedirectToAction("/");
        }

        // GET: /Job/Create
        public ActionResult Create()
        {
            ViewBag.City = (new RegionDropDown()).RegionList;
            return View();
        }

        // POST: /Job/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ViewJob viewJob)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account",
                           new { returnUrl = "/Job/Create", FormMethod.Get});
            }
            
            Job jobmodel = new Job();

            if (ModelState.IsValid)
            {
               // Console.WriteLine(fakejobmodel.region.Text.ToString());

                APIContext context = new APIContext();

                jobmodel.region = context.region.First(r => r.regionid == viewJob.region).region;


                jobmodel.district =  context.district.First(d => d.districtid == viewJob.district).district;
                jobmodel.suburb = context.suburb.First(d => d.suburbid == viewJob.suburb).suburb; ;
                jobmodel.description = viewJob.description;
                jobmodel.jobtype = viewJob.jobtype;
                jobmodel.title = viewJob.title;
                
                jobmodel.submitDate = DateTime.Now;
                
                switch (viewJob.duration)
                {
                    case "Now (24 Hrs)":
                        jobmodel.expireDate = jobmodel.submitDate.AddDays(1);
                        break;
                    case "Soon (48 Hrs)":
                        jobmodel.expireDate = jobmodel.submitDate.AddDays(2);
                        break;
                    case "Whenever (72 Hrs +)":
                        jobmodel.expireDate = jobmodel.submitDate.AddDays(3);
                        break;
                    default:
                        jobmodel.expireDate = jobmodel.submitDate.AddDays(1);
                        break; 
                }

                jobmodel.UserId = User.Identity.GetUserId();
                jobmodel.username = User.Identity.GetUserName();
                jobAPI.PostJob(jobmodel);

                List<string> images = ImageUpload();
                foreach(string image in images){
                    Photos photo = new Photos();
                    photo.jobid = jobmodel.jobid;
                    photo.photo = image;
                    context.photos.Add(photo);
                }
                context.SaveChanges();
                
                List<ServiceProviderDetails> providers = context.ServiceProvidersDetails.ToList();

                foreach (ServiceProviderDetails detail in providers)
                {
                    if (detail.userId != null)
                    {
                       

                        // Create the email object first, then add the properties.
                        SendGrid myMessage = SendGrid.GetInstance();
                        myMessage.AddTo(detail.email);
                        myMessage.From = new MailAddress("no.reply-notifications@GoodJob.co.nz", "GoodJob.co.nz");
                        myMessage.Subject = "New job - " + jobmodel.title;
                        myMessage.Text = "Job Description\n" + jobmodel.description + "\n" + "www.GoodJob.co.nz/Job/Details/" + jobmodel.jobid;

                        // Create credentials, specifying your user name and password.
                        var credentials = new NetworkCredential("azure_1e527e7b7ec0d7c5eb3d21f6d1643c1e@azure.com", "9sixwieb");

                        // Create a REST transport for sending email.
                        var transportREST = Web.GetInstance(credentials);

                        // Send the email.

Dont_Panic-MVC-API/Dont_Panic-MVC-API/Views/Job/Create.cshtml
@model Dont_Panic_MVC_API.Models.ViewJob
@using Dont_Panic_MVC_API.Controllers.API_Controllers;
@using Dont_Panic_MVC_API.Models.API_Models;


@{
    ViewBag.Title = "Post Job";
}
<br />
<script language="javascript" type="text/javascript">
    window.onload = function () {
        if (sessionStorage.jobtitle != null) {
            document.getElementById("title").value = sessionStorage.jobtitle;
            var jobselect = document.getElementById("jobtype");
            for (var i = 0; i < jobselect.length; i++) {
                if (jobselect.options[i].text == sessionStorage.jobtype) {
                    jobselect.options[i].selected = true;
                }
            }

            if (sessionStorage.jobdescription != null) {
                document.getElementById("description").value = sessionStorage.jobdescription;

                var regionselect = document.getElementById("region");
                for (var i = 0; i < regionselect.length; i++) {
                    if (regionselect.options[i].value == sessionStorage.jobregion) {
                        regionselect.options[i].selected = true;
                    }
                }



                var districtselect = document.getElementById("district");
                districtselect.innerHTML = sessionStorage.jobdistrict;

                districtselect.options[sessionStorage.jobdistrictselection].selected = true;


                var suburbselect = document.getElementById("suburb");
                suburbselect.innerHTML = sessionStorage.jobsuburb;
                suburbselect.options[sessionStorage.jobsuburbselection].selected = true;

                var durationselect = document.getElementById("duration");
                for (var i = 0; i < durationselect.length; i++) {
                    if (durationselect.options[i].value == sessionStorage.jobduration) {
                        durationselect.options[i].selected = true;
                    }
                }


            }
            sessionStorage.clear();

        }
        if (document.getElementById("region").value == "") {
            setDistrict(false);
            setSuburb(false);
        }
        else {
            setDistrict(true);
            if (document.getElementById("district").value == "") {
                setSuburb(false);
            }
            else {
                setSuburb(true);
            }
        }
    }


    function saveInformation(saveOrNot) {
        var titlebox = document.getElementById("title");
        var category = document.getElementById("jobtype");
        var suburb = document.getElementById("suburb");
        var description = document.getElementById("description");
        if (!saveOrNot) {
            if (titlebox.value.length > 0 && description.value.length > 0 && suburb.value > 0) {

                sessionStorage.jobtitle = titlebox.value;
                sessionStorage.jobtype = category.value;
                sessionStorage.jobdescription = description.value;
                sessionStorage.jobregion = document.getElementById("region").value;
                sessionStorage.jobdistrict = document.getElementById("district").innerHTML;
                sessionStorage.jobsuburb = document.getElementById("suburb").innerHTML;
                sessionStorage.jobdistrictselection = document.getElementById("district").value;
                sessionStorage.jobsuburbselection = document.getElementById("suburb").value;
                sessionStorage.jobduration = document.getElementById("duration").value;
            }
        }
        else {
            sessionStorage.clear();
        }


        if (titlebox.value.length > 0 && description.value.length > 0 && suburb.value > 0) {
            $('#createbutton').fadeOut('fast');
            var opts = {
                lines: 13, // The number of lines to draw
                length: 9, // The length of each line
                width: 3, // The line thickness
                radius: 8, // The radius of the inner circle
                corners: 1, // Corner roundness (0..1)
                rotate: 48, // The rotation offset
                direction: 1, // 1: clockwise, -1: counterclockwise
                color: '#65A592', // #rgb or #rrggbb or array of colors
                speed: 1.6, // Rounds per second
                trail: 79, // Afterglow percentage
                shadow: true, // Whether to render a shadow
                hwaccel: true, // Whether to use hardware acceleration
                className: 'spinner', // The CSS class to assign to the spinner
                zIndex: 2e9, // The z-index (defaults to 2000000000)
                top: 'auto', // Top position relative to parent in px
                left: 'auto' // Left position relative to parent in px
            };
            var target = document.getElementById('loadingzone');
            var spinner = new Spinner(opts).spin(target);
        }
    }

    var previousReg;
    function showHideSelect(select) {
        if (select.name == "region") {
            if (select.value != "") {
                setDistrict(true);
                if (previousReg != select.value) {
                    setSuburb(false);
                }

                previousReg = select.value;
            }
            else {
                setDistrict(false);
                setSuburb(false);
            }
        }
        else if (select.name == "district") {
            if (select.value != "") {
                setSuburb(true);
            }
            else {
                setSuburb(false);
            }
        }
    }
    function setDistrict(b) {
        var districtLabel = $("#districtLbl");
        var districtSelect = $("#district");
        if (b) {
            districtLabel.fadeIn("slow");
            districtSelect.fadeIn("slow");
        }
        else {
            districtLabel.fadeOut("slow");
            districtSelect.fadeOut("slow");
        }
    }

    function setSuburb(b) {
        var suburbSelect = $("#suburb");
        var suburbLabel = $("#suburbLbl");
        if (b) {
            suburbSelect.fadeIn("slow");
            suburbLabel.fadeIn("slow");
        }
        else {
            suburbSelect.fadeOut("slow");
            suburbLabel.fadeOut("slow");
        }

    }

    function feedback() {
        var input = $('#fileupload'),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.trigger('fileselect', [numFiles, label]);

        if (numFiles > 1) {
            $('#inputfeedback').val(numFiles.toString() + " images selected.");
        }
        else {
            $('#inputfeedback').val(label.toString());

        }
    }
</script>
<div class="container rounded-corners">
    <h2 class="centertext"><font color="#65B5A2">post</font> job</h2>
    <hr />
    @using (Html.BeginForm("Create", "Job", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="container-form">

            <div class="form-group">
                @Html.LabelFor(model => model.jobtype, new { @class = "control-label" })
                <select class="form-control" required id="jobtype" name="jobtype">
                    <option>Plumbing</option>
                    <option>Electrical</option>
                    <option>Business</option>
                    <option>Crafts</option>
                    <option>Design and web</option>
                    <option>Legal</option>
                    <option>Personal</option>
                    <option>Pets</option>
                    <option>Photography</option>
                    <option>Repair services</option>
                    <option>Writing/Translation</option>
                </select>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.title, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.title, new { @name = "title", @id = "title", @class = "form-control", @type = "text", @placeholder = "e.g. Blocked Drain" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, new { @class = "control-label" })
                <textarea rows="3" name="description" required id="description" class=" form-control"></textarea>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <div class="form-group">
                    <label class="control-label">What does it look like?</label>
                    <div class="input-group">
                        <span class="input-group-btn">
                            <span class="btn btn-default btn-file">
                                Browse…
                                <input id="fileupload" type="file" name="images" accept="image/x-png, image/gif, image/jpeg, image/jpg,image/png" onchange="feedback()" multiple>
                            </span>
                        </span>
                        <input id="inputfeedback" class="form-control" type="text" readonly="">
                    </div>
                </div>
            }


            <div class="form-group">
                @Html.LabelFor(model => model.region, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.region, (SelectList)ViewBag.City, "Select your region", new { @class = "form-control", @id = "region", onchange = "selectRegion(1);showHideSelect(this)" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.district, new { @class = "control-label", @id = "districtLbl" })
                @Html.DropDownListFor(model => model.district, Enumerable.Empty<SelectListItem>(), "Select your district", new { @class = "form-control", @id = "district", onchange = "selectRegion(2);showHideSelect(this)" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.suburb, new { @class = "control-label", @id = "suburbLbl" })
                @Html.DropDownListFor(model => model.suburb, Enumerable.Empty<SelectListItem>(), "Select your suburb", new { @class = "form-control", @id = "suburb", @onchange = "showHideSelect(this)" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.duration, new { @class = "control-label", @id = "durationLbl" })
                <select class="form-control" required id="duration" name="duration">
                    <option>Now (24 Hrs)</option>
                    <option>Soon (48 Hrs)</option>
                    <option>Whenever (72 Hrs +)</option>
                </select>
            </div>

            <div class="form-group">
                <input id="createbutton" type="submit" onclick="saveInformation(@User.Identity.IsAuthenticated);" value="Create" class="btn-dontpanic" />
                <div id="loadingzone"></div>
                <br />
                <br />
                @if (User.Identity.IsAuthenticated)
                {

                    <p>
                        @Html.ActionLink("Back to your jobs", "Index")
                    </p>
                }
                else
                {
                    <p>
                        @Html.ActionLink("Back", "Browse")
                    </p>

                }
            </div>
        </div>
    }

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/Areas.js")
}

Dont_Panic-MVC-API/Dont_Panic-MVC-API/Views/Job/Delete.cshtml
@model Dont_Panic_MVC_API.Models.API_Models.Job

@{
    ViewBag.Title = "Delete Job";
}

<div class="container">
    <h2>Confirm delete</h2>
    <h3>Are you sure you want to delete this job?</h3>
    <h4>Service providers that have contacted you will be notified of this job deletion.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobtype)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobtype)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default "/>
            @Html.ActionLink("Back to your jobs", "Index")
        </div>
    }
</div>

Dont_Panic-MVC-API/Dont_Panic-MVC-API/Views/Job/Index.cshtml
@model IEnumerable<Dont_Panic_MVC_API.Models.API_Models.Job>
@using Dont_Panic_MVC_API.Controllers.API_Controllers;
@using Dont_Panic_MVC_API.Models.API_Models;
@{
    ViewBag.Title = "Your jobs";

}

<br />
<div class="container drop-shadow browse-jobs-block">
    <h3 class="centertext"><font color="#65B5A2">your</font> jobs</h3>
    <br />
    @{
        if (Model.Count() == 0)
        {

            <p>
                You currently have no jobs active. @Html.ActionLink("Post a job now.", "Create", new { @style = "color:#65B5A2;" })
            </p>
        }

    }

    @foreach (var item in Model)
    {
        <div class="row job-block drop-shadow-lite">
            <br />
            @{
        PhotoAPI api = new PhotoAPI();
        Photos firstPhoto = api.getFirstPhoto(item.jobid);
            }

            @if (firstPhoto == null)
            {

                <div class="col-md-3"><a href="/Job/Details/@item.jobid"><img src="~/Images/nophotoavailable.jpg" class="img-rounded drop-shadow-lite img-responsive" width="200" height="200" /></a></div>

            }
            else
            {
                <div class="col-md-3"><a href="/Job/Details/@item.jobid"><img src="@Url.Content(firstPhoto.photo)" class="img-rounded drop-shadow-lite img-responsive " height="200" width="200" /></a></div>

            }




            <div class="col-md-9">
                <p>
                    @Html.ActionLink(item.title, "Details", new { id = item.jobid }, new { @style = "color:#497769;", @class = "job-block-title" })<br />
                    @item.description
                </p>

                <div class="row">
                    <div class="job-block-detail-left col-md-6">
                        @{
            TimeSpan timeSincePost = DateTime.Now - item.submitDate;
            string agoText;
                        }
                        @if (timeSincePost.Days > 1)
                        {
                            agoText = timeSincePost.Days.ToString() + " days ago";
                        }
                        else if (timeSincePost.Days == 1)
                        {
                            agoText = "a day ago";
                        }
                        else if (timeSincePost.Minutes > 1 && timeSincePost.Hours < 1)
                        {
                            agoText = timeSincePost.Minutes.ToString() + " minutes ago";
                        }
                        else if (timeSincePost.Minutes == 1)
                        {
                            agoText = timeSincePost.Minutes.ToString() + " minute ago";
                        }
                        else if (timeSincePost.Minutes < 1)
                        {
                            agoText = "less than a minute ago";
                        }
                        else if (timeSincePost.Hours > 1)
                        {
                            agoText = timeSincePost.Hours.ToString() + " hours ago";
                        }
                        else if (timeSincePost.Hours == 1)
                        {
                            agoText = "an hour ago";
                        }
                        else
                        {
                            agoText = "less than an hour ago";
                        }
                        <p class="text-primary" style="font-size:12px">
                            Category: @item.jobtype<br />Located in: @item.region
                            <br />Posted: @agoText
                        </p>
                    </div>
                    <div class="job-block-detail-right col-md-6">
                        @using (Html.BeginForm("InterestedPros", "Job", FormMethod.Get, new { id = "interestedForm"}))
                        {
                            @Html.Hidden("jobid", item.jobid);
                        }
                        <a href="#" onclick="javascript: document.getElementById('interestedForm').submit()"><p>@item.leadsAccquired interested pros</p></a>
                        <input type="button" onclick="location.href='/Job/Details/@item.jobid'" value="View Job" class="btn-dontpanic" />

                    </div>
                </div>
            </div>
        </div>
        <br />
    }



</div>

Dont_Panic-MVC-API/Dont_Panic-MVC-API/Views/Job/Previous.cshtml
@model IEnumerable<Dont_Panic_MVC_API.Models.API_Models.Job>
@using Dont_Panic_MVC_API.Controllers.API_Controllers;
@using Dont_Panic_MVC_API.Models.API_Models;

<script type="text/javascript" language="javascript">
    function showpic(id) {
        $('#' + id).modal('show');
    }
</script>

@{
    ViewBag.Title = "Previous Jobs";
}
@using Microsoft.AspNet.Identity;
@{
    Dont_Panic_MVC_API.API_Models.IdentityManager im = new Dont_Panic_MVC_API.API_Models.IdentityManager();

}

<br />



<div class="container drop-shadow browse-jobs-block">
    <h3 class="centertext"><font color="#65B5A2">previous</font> jobs</h3>
    <br />
    @if (Model.Count() == 0)
    {
        <p>
            You have no previous jobs.
            @if (im.UserContainsRole(User.Identity.GetUserId(), "User"))
            {
                @Html.ActionLink("Post a new job now.", "Create", new { @style = "color:#65B5A2;" })
            }
        </p>

    }
    else
    {
        <h5>These are your jobs that have expired</h5>
    }
    <br />
    @foreach (var item in Model)
    {
        <div class="row job-block drop-shadow-lite">
            <br />
            @{
        PhotoAPI api = new PhotoAPI();
        Photos firstPhoto = api.getFirstPhoto(item.jobid);
            }

            @if (firstPhoto == null)
            {

                <div class="col-md-3"><a href="/Job/Details/@item.jobid"><img src="~/Images/nophotoavailable.jpg" class="img-rounded drop-shadow-lite img-responsive" width="200" height="200" /></a></div>

            }
            else
            {
                <div class="col-md-3"><a href="/Job/Details/@item.jobid"><img src="@Url.Content(firstPhoto.photo)" class="img-rounded drop-shadow-lite img-responsive " height="200" width="200" /></a></div>



            }




            <div class="col-md-9">
                <p>
                    @Html.ActionLink(item.title, "Details", new { id = item.jobid }, new { @style = "color:#497769;", @class = "job-block-title" })<br />
                    @item.description
                </p>

                <div class="row">
                    <div class="job-block-detail-left col-md-6">
                        <p class="text-primary" style="font-size:12px">
                            Category: @item.jobtype<br />Located in: @item.region
                        </p>
                    </div>

                    <div class="job-block-detail-right col-md-6">
                        @using (Html.BeginForm("RepostJob", "Job", FormMethod.Post))
                        {
                            @Html.Hidden("jobid", @item.jobid);
                            <input type="submit" value="Repost Job" class="btn-dontpanic" />
                        }
                    </div>

                </div>
            </div>
        </div>
        <br />
    }

</div>